# Generated by Django 6.0.6 on 2026-06-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='seat_number',
            new_name='booking_code',
        ),
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_numbers',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(default='Bus', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_time',
            field=models.CharField(max_length=20),
        ),
    ]
