# Generated by Django 6.0.6 on 2026-06-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_seat_number_booking_booking_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(default='Bus', max_length=50),
        ),
    ]
