# Generated by Django 6.0.5 on 2026-06-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_weeklyschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='busschedule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='buses/'),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='bus_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
