# Generated by Django 6.0.6 on 2026-06-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_promotion_promoredemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='busschedule',
            name='days_of_week',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
