# Generated by Django 6.0.6 on 2026-06-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='busschedule',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
