# Generated by Django 6.0.6 on 2026-06-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_booking_checked_in_booking_checked_in_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
