# Generated by Django 6.0.5 on 2026-07-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_promotion_max_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
