# Generated by Django 6.0.5 on 2026-07-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_userprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('Staff', 'Staff'), ('Driver', 'Driver'), ('Cashier', 'Cashier'), ('Manager', 'Manager'), ('Security', 'Security'), ('Cleaner', 'Cleaner')], default='Staff', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffWorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='booking.staff')),
            ],
            options={
                'ordering': ['-date', 'check_in_time'],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
