# Generated by Django 6.0.5 on 2026-07-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_staff_staffworkrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='pin',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
